apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: kowsalya-namespace
  labels:
    app: bms
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000  
  selector:
    app: bms
